version: '3.4'
 
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd_02
    volumes:
      - './drive:/var/opt/mssql'
    networks:
      - movieappnetwork
      
  movie.webapi:
    image: movie.api
    env_file:
      - ".env"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${DOCKER_SERVER_PORT_FORWARD}:${SERVER_PORT}"
    build:
      context: ..
      dockerfile: src/Movie.Api/Dockerfile
    networks:
      - movieappnetwork
    depends_on: [ mssql ]
    
  movie.web:
    image: movie.web
    env_file:
      - ".env"
    networks:
      - movieappnetwork
    ports:
      - "${DOCKER_CLIENT_PORT_FORWARD}:${CLIENT_PORT}"
    build:
      context: ..
      dockerfile: src/Movie.Api/ClientApp/Dockerfile
    volumes:
      - "/app"
    environment:
        PROXY_API: "http://${CLIENT_IP}:${DOCKER_SERVER_PORT_FORWARD}"
    depends_on: [movie.webapi]

networks:
  movieappnetwork:
    external: false