version: '3.4'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "mygpi_user"
      ACCEPT_EULA: "mygpi_pa$$"
      
  movie.webapi:
    image: movie.api
    build:
      context: .
      dockerfile: ../src/Movie.Api/Dockerfile
      
  movie.web:
    image: movie.web
    build:
      context: .
      dockerfile: ../src/Movie.Api/ClientApp/Dockerfile