version: '3.4'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "sa"
      ACCEPT_EULA: "Pass@word"
      
  movie.webapi:
    image: movie.api
    build:
      context: ..
      dockerfile: src/Movie.Api/Dockerfile
    depends_on: [ mssql ]
    
  movie.web:
    image: movie.web
    build:
      context: ..
      dockerfile: src/Movie.Api/ClientApp/Dockerfile