// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie.Infrastructure.Context;

#nullable disable

namespace Movie.Infrastructure.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20230114234402_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movie.Infrastructure.Domain.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Synopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64264ce1-4299-4961-8429-f26b02405379"),
                            Rating = "7",
                            ReleaseDate = new DateTime(1988, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A couple of recently deceased ghosts contract the services of a \"bio-exorcist\" in order to remove the obnoxious new owners of their house.",
                            Title = "Beetlejuice"
                        },
                        new
                        {
                            Id = new Guid("7feae097-4d61-4287-9dd4-737560a90b9f"),
                            Rating = "8",
                            ReleaseDate = new DateTime(1984, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The Cotton Club was a famous night club in Harlem. The story follows the people that visited the club, those that ran it, and is peppered with the Jazz music that made it so famous.",
                            Title = "The Cotton Club"
                        },
                        new
                        {
                            Id = new Guid("e1307ac2-a1aa-48b9-8983-c1dd93213f64"),
                            Rating = "6",
                            ReleaseDate = new DateTime(1994, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = new Guid("a0822b4e-ba2e-4350-8817-f923a36576d2"),
                            Rating = "0",
                            ReleaseDate = new DateTime(1986, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An American reporter goes to the Australian outback to meet an eccentric crocodile poacher and invites him to New York City.",
                            Title = "Crocodile Dundee"
                        },
                        new
                        {
                            Id = new Guid("54e8d556-ede4-4e79-a418-fa2af86c5280"),
                            Rating = "8",
                            ReleaseDate = new DateTime(2008, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A dramatization of the 20 July assassination and political coup plot by desperate renegade German Army officers against Hitler during World War II.",
                            Title = "Valkyrie"
                        },
                        new
                        {
                            Id = new Guid("86c74c81-c727-4438-acc3-17eccd680d29"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2007, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.",
                            Title = "Ratatouille"
                        },
                        new
                        {
                            Id = new Guid("a9c2e2cd-d42f-47c8-9c79-a76d0f3535ed"),
                            Rating = "6",
                            ReleaseDate = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer.",
                            Title = "City of God"
                        },
                        new
                        {
                            Id = new Guid("669d8b52-37d3-4a46-98e1-86a07c9014b6"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A man juggles searching for his wife's murderer and keeping his short-term memory loss from being an obstacle.",
                            Title = "Memento"
                        },
                        new
                        {
                            Id = new Guid("84b59473-330d-433b-babe-12788d8ef2d3"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
                            Title = "The Intouchables"
                        },
                        new
                        {
                            Id = new Guid("41355d9d-98a3-4f2e-a51b-47c830e8cadf"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2007, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In a countryside town bordering on a magical land, a young man makes a promise to his beloved that he'll retrieve a fallen star by venturing into the magical realm.",
                            Title = "Stardust"
                        },
                        new
                        {
                            Id = new Guid("a6cfe4cd-7753-4742-94a0-e0875f4eabd2"),
                            Rating = "5",
                            ReleaseDate = new DateTime(2006, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "As the Mayan kingdom faces its decline, the rulers insist the key to prosperity is to build more temples and offer human sacrifices. Jaguar Paw, a young man captured for sacrifice, flees to avoid his fate.",
                            Title = "Apocalypto"
                        },
                        new
                        {
                            Id = new Guid("76e4ccf5-420c-401e-9402-5ee4c09ed909"),
                            Rating = "5",
                            ReleaseDate = new DateTime(1976, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A mentally unstable Vietnam War veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action, attempting to save a preadolescent prostitute in the process.",
                            Title = "Taxi Driver"
                        },
                        new
                        {
                            Id = new Guid("7fb8e533-e6df-48bd-bc04-502c53ac7c72"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2007, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
                            Title = "No Country for Old Men"
                        },
                        new
                        {
                            Id = new Guid("785213ac-34f2-4bc7-bb48-6687446e16cc"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2009, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An alien civilization is invaded by Astronaut Chuck Baker, who believes that the planet was uninhabited. Wanted by the military, Baker must get back to his ship before it goes into orbit without him.",
                            Title = "Planet 51"
                        },
                        new
                        {
                            Id = new Guid("574a34b2-0fc5-4d3b-871f-00dfbf4ff9be"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In 2074, when the mob wants to get rid of someone, the target is sent into the past, where a hired gun awaits - someone like Joe - who one day learns the mob wants to 'close the loop' by sending back Joe's future self for assassination.",
                            Title = "Looper"
                        },
                        new
                        {
                            Id = new Guid("92e795c7-da32-4fa7-b4de-b52b385ce81d"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "When a shy groom practices his wedding vows in the inadvertent presence of a deceased young woman, she rises from the grave assuming he has married her.",
                            Title = "Corpse Bride"
                        },
                        new
                        {
                            Id = new Guid("50d78d88-f501-4778-908f-7d588b4ac928"),
                            Rating = "5",
                            ReleaseDate = new DateTime(1949, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.",
                            Title = "The Third Man"
                        },
                        new
                        {
                            Id = new Guid("11017d57-f0d1-47c1-8c71-a80e2e1a6f70"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Twenty-something Richard travels to Thailand and finds himself in possession of a strange map. Rumours state that it leads to a solitary beach paradise, a tropical bliss - excited and intrigued, he sets out to find it.",
                            Title = "The Beach"
                        },
                        new
                        {
                            Id = new Guid("778bd936-0055-42a6-9797-cf5224762929"),
                            Rating = "8",
                            ReleaseDate = new DateTime(1983, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In Miami in 1980, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.",
                            Title = "Scarface"
                        },
                        new
                        {
                            Id = new Guid("bb5c7948-6504-400f-b0c1-7639ece49fb3"),
                            Rating = "9",
                            ReleaseDate = new DateTime(1986, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Morbid biographical story of Sid Vicious, bassist with British punk group the Sex Pistols, and his girlfriend Nancy Spungen. When the Sex Pistols break up after their fateful US tour, ...",
                            Title = "Sid and Nancy"
                        },
                        new
                        {
                            Id = new Guid("3c32ea45-d1f5-4c86-ba33-3288008d3d63"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A committed dancer wins the lead role in a production of Tchaikovsky's \"Swan Lake\" only to find herself struggling to maintain her sanity.",
                            Title = "Black Swan"
                        },
                        new
                        {
                            Id = new Guid("6a2f5383-7958-48ea-a6cd-bd08997cc3f2"),
                            Rating = "8",
                            ReleaseDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = new Guid("9c7d4465-9edd-40ab-8a1d-38d1471ba311"),
                            Rating = "0",
                            ReleaseDate = new DateTime(1978, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An in-depth examination of the ways in which the U.S. Vietnam War impacts and disrupts the lives of people in a small industrial town in Pennsylvania.",
                            Title = "The Deer Hunter"
                        },
                        new
                        {
                            Id = new Guid("9d2b6c68-4986-448a-b670-2b78cb4899f5"),
                            Rating = "2",
                            ReleaseDate = new DateTime(1997, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Holden and Banky are comic book artists. Everything's going good for them until they meet Alyssa, also a comic book artist. Holden falls for her, but his hopes are crushed when he finds out she's gay.",
                            Title = "Chasing Amy"
                        },
                        new
                        {
                            Id = new Guid("a543e3f3-cfb1-4f03-adef-0ee698ddd699"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
                            Title = "Django Unchained"
                        },
                        new
                        {
                            Id = new Guid("b6e03c0b-5000-4d54-8551-7993c15a6eef"),
                            Rating = "3",
                            ReleaseDate = new DateTime(1991, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.",
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = new Guid("cbe9006e-59d2-4d7a-a981-77e1b47e3ab8"),
                            Rating = "7",
                            ReleaseDate = new DateTime(1999, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
                            Title = "American Beauty"
                        },
                        new
                        {
                            Id = new Guid("82af1e64-d596-4dda-b95f-cde4580baa10"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
                            Title = "Snatch"
                        },
                        new
                        {
                            Id = new Guid("1b06ad8f-0471-4ffe-8067-9ba6c1a98356"),
                            Rating = "1",
                            ReleaseDate = new DateTime(1978, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Billy Hayes, an American college student, is caught smuggling drugs out of Turkey and thrown into prison.",
                            Title = "Midnight Express"
                        },
                        new
                        {
                            Id = new Guid("4d853e68-d9bd-4ff4-8f12-9be2fe2d702a"),
                            Rating = "9",
                            ReleaseDate = new DateTime(1994, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = new Guid("6dfcebf5-2ccd-4ae9-a0ea-0bf2b0dbc176"),
                            Rating = "6",
                            ReleaseDate = new DateTime(1998, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A botched card game in London triggers four friends, thugs, weed-growers, hard gangsters, loan sharks and debt collectors to collide with each other in a series of unexpected events, all for the sake of weed, cash and two antique shotguns.",
                            Title = "Lock, Stock and Two Smoking Barrels"
                        },
                        new
                        {
                            Id = new Guid("f6a6f7b4-f762-4d62-85ad-cd1570135447"),
                            Rating = "5",
                            ReleaseDate = new DateTime(2006, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A case of mistaken identity lands Slevin into the middle of a war being plotted by two of the city's most rival crime bosses: The Rabbi and The Boss. Slevin is under constant surveillance by relentless Detective Brikowski as well as the infamous assassin Goodkat and finds himself having to hatch his own ingenious plot to get them before they get him.",
                            Title = "Lucky Number Slevin"
                        },
                        new
                        {
                            Id = new Guid("2113b429-0795-45b0-9bf5-eec19b8877c5"),
                            Rating = "0",
                            ReleaseDate = new DateTime(1954, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A wheelchair-bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder.",
                            Title = "Rear Window"
                        },
                        new
                        {
                            Id = new Guid("1dc38b5d-8f54-4c74-a39a-dfd4b09b04b1"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2006, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            Id = new Guid("26c824e9-a9ae-45a5-bcf8-b6142f6ca4e8"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In 1954, a U.S. marshal investigates the disappearance of a murderess who escaped from a hospital for the criminally insane.",
                            Title = "Shutter Island"
                        },
                        new
                        {
                            Id = new Guid("dd624846-c28c-49cc-a20f-9cbda07e1ce0"),
                            Rating = "7",
                            ReleaseDate = new DateTime(1992, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.",
                            Title = "Reservoir Dogs"
                        },
                        new
                        {
                            Id = new Guid("b3b67f33-08e3-46aa-8ceb-4e2d4838d20b"),
                            Rating = "9",
                            ReleaseDate = new DateTime(1980, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A family heads to an isolated hotel for the winter where an evil and spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.",
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = new Guid("77c43127-9686-4a90-b5d7-5fb4f52c09b2"),
                            Rating = "5",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "While on a trip to Paris with his fiancée's family, a nostalgic screenwriter finds himself mysteriously going back to the 1920s everyday at midnight.",
                            Title = "Midnight in Paris"
                        },
                        new
                        {
                            Id = new Guid("231fa6c5-ed4e-41b6-81fa-2a9019239805"),
                            Rating = "4",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In 19th-century France, Jean Valjean, who for decades has been hunted by the ruthless policeman Javert after breaking parole, agrees to care for a factory worker's daughter. The decision changes their lives forever.",
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = new Guid("434d99eb-06b0-498c-911a-c94ee6c55426"),
                            Rating = "5",
                            ReleaseDate = new DateTime(1997, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "As corruption grows in 1950s LA, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.",
                            Title = "L.A. Confidential"
                        },
                        new
                        {
                            Id = new Guid("3b051f3f-c829-4be9-9399-6b187eafb289"),
                            Rating = "8",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Oakland A's general manager Billy Beane's successful attempt to assemble a baseball team on a lean budget by employing computer-generated analysis to acquire new players.",
                            Title = "Moneyball"
                        },
                        new
                        {
                            Id = new Guid("97b5f83e-f978-4483-8e68-89b2c0a1f9ef"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2009, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.",
                            Title = "The Hangover"
                        },
                        new
                        {
                            Id = new Guid("584bafa9-bfaf-4d7b-b1a4-b5aa0a7d4e9f"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Jep Gambardella has seduced his way through the lavish nightlife of Rome for decades, but after his 65th birthday and a shock from the past, Jep looks past the nightclubs and parties to find a timeless landscape of absurd, exquisite beauty.",
                            Title = "The Great Beauty"
                        },
                        new
                        {
                            Id = new Guid("f2c29fe0-6540-402f-811f-f08f8715d724"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2008, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, a Hmong teenager who tried to steal Kowalski's prized possession: a 1972 Gran Torino.",
                            Title = "Gran Torino"
                        },
                        new
                        {
                            Id = new Guid("bd4f41ff-de49-416d-973d-182e5c860182"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2009, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A tale of friendship between two unlikely pen pals: Mary, a lonely, eight-year-old girl living in the suburbs of Melbourne, and Max, a forty-four-year old, severely obese man living in New York.",
                            Title = "Mary and Max"
                        },
                        new
                        {
                            Id = new Guid("d85b8855-8ccf-4a11-ad2a-c5d15a69870e"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An airline pilot saves almost all his passengers on his malfunctioning airliner which eventually crashed, but an investigation into the accident reveals something troubling.",
                            Title = "Flight"
                        },
                        new
                        {
                            Id = new Guid("527f94fe-c52f-4feb-a957-f75dbe63e852"),
                            Rating = "9",
                            ReleaseDate = new DateTime(1975, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A criminal pleads insanity after getting into trouble again and once in the mental institution rebels against the oppressive nurse and rallies up the scared patients.",
                            Title = "One Flew Over the Cuckoo's Nest"
                        },
                        new
                        {
                            Id = new Guid("7b4ba605-16cc-4a32-8c02-adf655b06bf0"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
                            Title = "Requiem for a Dream"
                        },
                        new
                        {
                            Id = new Guid("318edb35-5717-4e25-8bba-33e6309a0718"),
                            Rating = "1",
                            ReleaseDate = new DateTime(1998, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An insurance salesman/adjuster discovers his entire life is actually a television show.",
                            Title = "The Truman Show"
                        },
                        new
                        {
                            Id = new Guid("9479d99d-c1bb-470c-bc6b-d66a00bc2919"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A silent movie star meets a young dancer, but the arrival of talking pictures sends their careers in opposite directions.",
                            Title = "The Artist"
                        },
                        new
                        {
                            Id = new Guid("017e640a-f061-4157-a148-48650d17a0ed"),
                            Rating = "2",
                            ReleaseDate = new DateTime(1994, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = new Guid("7d24ba33-c836-44ff-b99d-11f34f3a11b8"),
                            Rating = "6",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug. Bilbo Baggins is in possession of a mysterious and magical ring.",
                            Title = "The Hobbit: The Desolation of Smaug"
                        },
                        new
                        {
                            Id = new Guid("6b5a6d57-784c-4458-8bcf-be8ec3089734"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2008, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Two girlfriends on a summer holiday in Spain become enamored with the same painter, unaware that his ex-wife, with whom he has a tempestuous relationship, is about to re-enter the picture.",
                            Title = "Vicky Cristina Barcelona"
                        },
                        new
                        {
                            Id = new Guid("a917aa04-dc24-4d26-b533-3cc7371d988d"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2008, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A Mumbai teen reflects on his upbringing in the slums when he is accused of cheating on the Indian Version of \"Who Wants to be a Millionaire?\"",
                            Title = "Slumdog Millionaire"
                        },
                        new
                        {
                            Id = new Guid("a1edafd7-6fe0-4c88-a780-132962905653"),
                            Rating = "4",
                            ReleaseDate = new DateTime(2003, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.",
                            Title = "Lost in Translation"
                        },
                        new
                        {
                            Id = new Guid("fff4692f-4a87-4df9-8dc5-7d28bedf24f8"),
                            Rating = "6",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "At a turning point in his life, a former tennis pro falls for an actress who happens to be dating his friend and soon-to-be brother-in-law.",
                            Title = "Match Point"
                        },
                        new
                        {
                            Id = new Guid("a927e549-daa8-432a-86a2-85e16ff0e52f"),
                            Rating = "7",
                            ReleaseDate = new DateTime(1960, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.",
                            Title = "Psycho"
                        },
                        new
                        {
                            Id = new Guid("401dc13c-220a-4238-adda-c399384537d4"),
                            Rating = "0",
                            ReleaseDate = new DateTime(1959, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies, and is pursued across the country while he looks for a way to survive.",
                            Title = "North by Northwest"
                        },
                        new
                        {
                            Id = new Guid("da2e8933-2cbd-4d75-a90c-47fca26154b1"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2008, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The animals try to fly back to New York City, but crash-land on an African wildlife refuge, where Alex is reunited with his parents.",
                            Title = "Madagascar: Escape 2 Africa"
                        },
                        new
                        {
                            Id = new Guid("f171bd55-9f09-42ee-9513-7cc7699e95b9"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "When Gru, the world's most super-bad turned super-dad has been recruited by a team of officials to stop lethal muscle and a host of Gru's own, He has to fight back with new gadgetry, cars, and more minion madness.",
                            Title = "Despicable Me 2"
                        },
                        new
                        {
                            Id = new Guid("fa4b371c-291b-4586-a8af-985f81ed6e78"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Traudl Junge, the final secretary for Adolf Hitler, tells of the Nazi dictator's final days in his Berlin bunker at the end of WWII.",
                            Title = "Downfall"
                        },
                        new
                        {
                            Id = new Guid("1bfad6cd-910c-4518-b09d-8a7cc234185b"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Spoiled by their upbringing with no idea what wild life is really like, four animals from New York Central Zoo escape, unwittingly assisted by four absconding penguins, and find themselves in Madagascar, among a bunch of merry lemurs",
                            Title = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("40b8c13d-ef5a-405a-ad91-b106bdf10b4b"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Alex, Marty, Gloria and Melman are still fighting to get home to their beloved Big Apple. Their journey takes them through Europe where they find the perfect cover: a traveling circus, which they reinvent - Madagascar style.",
                            Title = "Madagascar 3: Europe's Most Wanted"
                        },
                        new
                        {
                            Id = new Guid("72a11e42-b6c4-4e5e-b167-6d052ed4f135"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "On a mission to rid society of its most repellent citizens, terminally ill Frank makes an unlikely accomplice in 16-year-old Roxy.",
                            Title = "God Bless America"
                        },
                        new
                        {
                            Id = new Guid("fa034506-6495-401f-b434-69deaa33dd68"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea, and the co-founder who was later squeezed out of the business.",
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = new Guid("4ded06dd-a108-4942-9ba2-569eb5e842e6"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
                            Title = "The Pianist"
                        },
                        new
                        {
                            Id = new Guid("0347bd4c-7b6e-41f4-95c2-601ac8a1480c"),
                            Rating = "4",
                            ReleaseDate = new DateTime(1993, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Uruguayan rugby team stranded in the snow swept Andes are forced to use desperate measures to survive after a plane crash.",
                            Title = "Alive"
                        },
                        new
                        {
                            Id = new Guid("2b6f7552-7bba-471f-ac9a-7793acf83e68"),
                            Rating = "2",
                            ReleaseDate = new DateTime(1942, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In Casablanca, Morocco in December 1941, a cynical American expatriate meets a former lover, with unforeseen complications.",
                            Title = "Casablanca"
                        },
                        new
                        {
                            Id = new Guid("eaedeb98-182f-4ce9-b35c-1b86b4ba42c9"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2007, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In 1970s America, a detective works to bring down the drug empire of Frank Lucas, a heroin kingpin from Manhattan, who is smuggling the drug into the country from the Far East.",
                            Title = "American Gangster"
                        },
                        new
                        {
                            Id = new Guid("6b7d4bb1-8c57-4270-97a9-7ada0100ad3b"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The true story of Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars' worth of checks as a Pan Am pilot, doctor, and legal prosecutor.",
                            Title = "Catch Me If You Can"
                        },
                        new
                        {
                            Id = new Guid("eacc2d4a-dfd2-49bb-9607-93694236b7e2"),
                            Rating = "0",
                            ReleaseDate = new DateTime(1998, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
                            Title = "American History X"
                        },
                        new
                        {
                            Id = new Guid("026df438-fd17-407a-9005-fae516f325d8"),
                            Rating = "6",
                            ReleaseDate = new DateTime(1995, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Greed, deception, money, power, and murder occur between two best friends, a mafia underboss and a casino owner, for a trophy wife over a gambling empire.",
                            Title = "Casino"
                        },
                        new
                        {
                            Id = new Guid("d37c6825-4d0d-44ae-88d1-51bde1b8ca75"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2007, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Captain Barbossa, Will Turner and Elizabeth Swann must sail off the edge of the map, navigate treachery and betrayal, find Jack Sparrow, and make their final alliances for one last decisive battle.",
                            Title = "Pirates of the Caribbean: At World's End"
                        },
                        new
                        {
                            Id = new Guid("b50dc598-241e-4101-9ef6-3fd271370611"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Jack Sparrow and Barbossa embark on a quest to find the elusive fountain of youth, only to discover that Blackbeard and his daughter are after it too.",
                            Title = "Pirates of the Caribbean: On Stranger Tides"
                        },
                        new
                        {
                            Id = new Guid("37be3fb0-eaea-4a57-ad36-6a3cccc23ca7"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Los Angeles citizens with vastly separate lives collide in interweaving stories of race, loss and redemption.",
                            Title = "Crash"
                        },
                        new
                        {
                            Id = new Guid("89cdad47-21ec-4a3f-a551-2911399d1436"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2003, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Blacksmith Will Turner teams up with eccentric pirate \"Captain\" Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies, who are now undead.",
                            Title = "Pirates of the Caribbean: The Curse of the Black Pearl"
                        },
                        new
                        {
                            Id = new Guid("0c362896-26af-40aa-a858-3589b1506031"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2003, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = new Guid("57c0c706-cd4e-4a3d-a861-01cd2f39e1ed"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2003, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.",
                            Title = "Oldboy"
                        },
                        new
                        {
                            Id = new Guid("13bfa42d-a566-4cf3-bec7-99f1d81c3128"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A woman and her daughter open a chocolate shop in a small French village that shakes up the rigid morality of the community.",
                            Title = "Chocolat"
                        },
                        new
                        {
                            Id = new Guid("c23beacb-d49c-4865-b68c-f5992bfb3362"),
                            Rating = "5",
                            ReleaseDate = new DateTime(2006, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Armed with a licence to kill, Secret Agent James Bond sets out on his first mission as 007 and must defeat a weapons dealer in a high stakes game of poker at Casino Royale, but things are not what they seem.",
                            Title = "Casino Royale"
                        },
                        new
                        {
                            Id = new Guid("50542fd5-2451-4176-a377-0ae62b580cce"),
                            Rating = "8",
                            ReleaseDate = new DateTime(2008, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
                            Title = "WALL·E"
                        },
                        new
                        {
                            Id = new Guid("5ac03097-2684-4649-8b4c-b15a46372ecc"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
                            Title = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = new Guid("182b7f27-94ea-4aca-9723-941808414a42"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2008, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The mythical world starts a rebellion against humanity in order to rule the Earth, so Hellboy and his team must save the world from the rebellious creatures.",
                            Title = "Hellboy II: The Golden Army"
                        },
                        new
                        {
                            Id = new Guid("5c2e6074-0a0c-4235-bb0a-f4ff9468347d"),
                            Rating = "3",
                            ReleaseDate = new DateTime(1950, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A hack screenwriter writes a screenplay for a former silent-film star who has faded into Hollywood obscurity.",
                            Title = "Sunset Boulevard"
                        },
                        new
                        {
                            Id = new Guid("78d44099-26fd-4c00-9891-129ec7aa01b0"),
                            Rating = "8",
                            ReleaseDate = new DateTime(2006, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A 17-year-old boy buys mini-cameras and displays the footage online at I-see-you.com. The cash rolls in as the site becomes a major hit. Everyone seems to have fun until it all comes crashing down....",
                            Title = "I-See-You.Com"
                        },
                        new
                        {
                            Id = new Guid("ead9fe5f-d64b-45b2-b20b-f73cef966984"),
                            Rating = "6",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            Id = new Guid("e5ce1228-c910-4d4e-8f37-d38540c94766"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Mere seconds before the Earth is to be demolished by an alien construction crew, journeyman Arthur Dent is swept off the planet by his friend Ford Prefect, a researcher penning a new edition of \"The Hitchhiker's Guide to the Galaxy.\"",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("56db696a-812e-4c83-9c16-f0ef5e0afa29"),
                            Rating = "7",
                            ReleaseDate = new DateTime(1984, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
                            Title = "Once Upon a Time in America"
                        },
                        new
                        {
                            Id = new Guid("33665257-0209-4afc-846f-a07f3ff9699f"),
                            Rating = "6",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A veteran assigned to extract Earth's remaining resources begins to question what he knows about his mission and himself.",
                            Title = "Oblivion"
                        },
                        new
                        {
                            Id = new Guid("c54e7365-45ea-4be2-8d01-20b998f198cf"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In a future British tyranny, a shadowy freedom fighter, known only by the alias of \"V\", plots to overthrow it with the help of a young woman.",
                            Title = "V for Vendetta"
                        },
                        new
                        {
                            Id = new Guid("b23bf1bc-8e74-4f2a-a28f-e5989707d359"),
                            Rating = "2",
                            ReleaseDate = new DateTime(1997, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A genetically inferior man assumes the identity of a superior one in order to pursue his lifelong dream of space travel.",
                            Title = "Gattaca"
                        },
                        new
                        {
                            Id = new Guid("e8999640-6ae5-40ac-9c89-f49e0f4240e6"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own.",
                            Title = "Silver Linings Playbook"
                        },
                        new
                        {
                            Id = new Guid("34977081-273f-408d-aec6-eb11d1950071"),
                            Rating = "5",
                            ReleaseDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Nineteen-year-old Alice returns to the magical world from her childhood adventure, where she reunites with her old friends and learns of her true destiny: to end the Red Queen's reign of terror.",
                            Title = "Alice in Wonderland"
                        },
                        new
                        {
                            Id = new Guid("489f0844-6aa7-46f3-9660-55a19411462d"),
                            Rating = "3",
                            ReleaseDate = new DateTime(1982, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Gandhi's character is fully explained as a man of nonviolence. Through his patience, he is able to drive the British out of the subcontinent. And the stubborn nature of Jinnah and his commitment towards Pakistan is portrayed.",
                            Title = "Gandhi"
                        },
                        new
                        {
                            Id = new Guid("bd3becc3-2a34-4c62-be06-c68996092c9d"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "As a war between humankind and monstrous sea creatures wages on, a former pilot and a trainee are paired up to drive a seemingly obsolete special weapon in a desperate effort to save the world from the apocalypse.",
                            Title = "Pacific Rim"
                        },
                        new
                        {
                            Id = new Guid("97b2592f-c044-480f-9945-ca1ee361ca28"),
                            Rating = "5",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A murder mystery brings together a private eye, a struggling actress, and a thief masquerading as an actor.",
                            Title = "Kiss Kiss Bang Bang"
                        },
                        new
                        {
                            Id = new Guid("70c3cee8-0605-4b2b-b0e6-97ea9d942e3e"),
                            Rating = "4",
                            ReleaseDate = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An older British reporter vies with a young U.S. doctor for the affections of a beautiful Vietnamese woman.",
                            Title = "The Quiet American"
                        },
                        new
                        {
                            Id = new Guid("38dc4bcd-370a-46a7-91c8-6e6900cfb365"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An exploration of how the actions of individual lives impact one another in the past, present and future, as one soul is shaped from a killer into a hero, and an act of kindness ripples across centuries to inspire a revolution.",
                            Title = "Cloud Atlas"
                        },
                        new
                        {
                            Id = new Guid("3cc8bd9b-515e-4488-85f6-db4ba8d2ea84"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The story of a tourist family in Thailand caught in the destruction and chaotic aftermath of the 2004 Indian Ocean tsunami.",
                            Title = "The Impossible"
                        },
                        new
                        {
                            Id = new Guid("d2d18d25-a2a4-4f4f-ac61-6007a41e56ad"),
                            Rating = "2",
                            ReleaseDate = new DateTime(1930, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A young soldier faces profound disillusionment in the soul-destroying horror of World War I.",
                            Title = "All Quiet on the Western Front"
                        },
                        new
                        {
                            Id = new Guid("b8c460a6-0608-4dc4-a05f-ab8a257c39d7"),
                            Rating = "8",
                            ReleaseDate = new DateTime(1996, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "At the close of WWII, a young nurse tends to a badly-burned plane crash victim. His past is shown in flashbacks, revealing an involvement in a fateful love affair.",
                            Title = "The English Patient"
                        },
                        new
                        {
                            Id = new Guid("1c9e820a-80cf-477b-b710-7d757c672572"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In 1985 Dallas, electrician and hustler Ron Woodroof works around the system to help AIDS patients get the medication they need after he is diagnosed with the disease.",
                            Title = "Dallas Buyers Club"
                        },
                        new
                        {
                            Id = new Guid("e06cfe8b-8d69-4e10-ad3f-b378e3faf9ab"),
                            Rating = "4",
                            ReleaseDate = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A biography of artist Frida Kahlo, who channeled the pain of a crippling injury and her tempestuous marriage into her work.",
                            Title = "Frida"
                        },
                        new
                        {
                            Id = new Guid("d5486a74-bb80-4b49-97d6-d5f5734cf603"),
                            Rating = "8",
                            ReleaseDate = new DateTime(1995, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.",
                            Title = "Before Sunrise"
                        },
                        new
                        {
                            Id = new Guid("74306c45-696d-4ff8-bfd2-946b39495595"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "American journalist Paul Kemp takes on a freelance job in Puerto Rico for a local newspaper during the 1960s and struggles to find a balance between island culture and the expatriates who live there.",
                            Title = "The Rum Diary"
                        },
                        new
                        {
                            Id = new Guid("50dcc1de-47ca-44c7-a57c-4c3e8e0b10a5"),
                            Rating = "6",
                            ReleaseDate = new DateTime(2003, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An American military advisor embraces the Samurai culture he was hired to destroy after he is captured in battle.",
                            Title = "The Last Samurai"
                        },
                        new
                        {
                            Id = new Guid("bf04b865-02e2-4ed4-bc09-a41cc56ff635"),
                            Rating = "1",
                            ReleaseDate = new DateTime(1974, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption and murder.",
                            Title = "Chinatown"
                        },
                        new
                        {
                            Id = new Guid("51052efb-a8c5-46b3-afeb-fa30d411ec1e"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "After he is threatened during a confession, a good-natured priest must battle the dark forces closing in around him.",
                            Title = "Calvary"
                        },
                        new
                        {
                            Id = new Guid("9bcea16b-b833-4e06-9243-d4ade295afbe"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Nine years after Jesse and Celine first met, they encounter each other again on the French leg of Jesse's book tour.",
                            Title = "Before Sunset"
                        },
                        new
                        {
                            Id = new Guid("718478ff-7f55-4bb9-bd0e-07dfa731cbd7"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2001, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = new Guid("30cc0b0b-9135-42a7-8de4-5f2729885942"),
                            Rating = "0",
                            ReleaseDate = new DateTime(1992, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "This story is set in 1930, at the time when French colonial rule in Indochina is ending. A widowed French woman who works in the rubber fields, raises a Vietnamese princess as if she was ...",
                            Title = "Indochine"
                        },
                        new
                        {
                            Id = new Guid("36c4d221-b3bb-4cd6-92fa-f72e64744415"),
                            Rating = "4",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Illustrated upon the progress of his latest Broadway play, a former popular actor's struggle to cope with his current life as a wasted actor is shown.",
                            Title = "Birdman or (The Unexpected Virtue of Ignorance)"
                        },
                        new
                        {
                            Id = new Guid("fddcf485-700e-4828-866b-ea5babf471fa"),
                            Rating = "6",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The life of Mason, from early childhood to his arrival at college.",
                            Title = "Boyhood"
                        },
                        new
                        {
                            Id = new Guid("8d1b6d1b-a996-454c-b4e2-d923ec248cf3"),
                            Rating = "2",
                            ReleaseDate = new DateTime(1957, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
                            Title = "12 Angry Men"
                        },
                        new
                        {
                            Id = new Guid("8acccb44-676f-465e-b6d4-a92730ea5a65"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians.",
                            Title = "The Imitation Game"
                        },
                        new
                        {
                            Id = new Guid("ca821fb7-ccb6-47a7-aa64-7102850a1df3"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = new Guid("ce9bb7fc-1ef5-4cc7-928b-eff9d4831d13"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2006, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A frustrated, unemployed teacher joining forces with a scammer and his girlfriend in a blackmailing scheme.",
                            Title = "Big Nothing"
                        },
                        new
                        {
                            Id = new Guid("f1dc4fec-9070-4ed3-aa41-bf059c3d47f9"),
                            Rating = "0",
                            ReleaseDate = new DateTime(1981, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The claustrophobic world of a WWII German U-boat; boredom, filth, and sheer terror.",
                            Title = "Das Boot"
                        },
                        new
                        {
                            Id = new Guid("e2ba0b51-2355-4086-bc9a-aac0ccdd5444"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Princess Fiona's parents invite her and Shrek to dinner to celebrate her marriage. If only they knew the newlyweds were both ogres.",
                            Title = "Shrek 2"
                        },
                        new
                        {
                            Id = new Guid("d3e6abe2-8231-4c76-a523-d6d3a86f5879"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A film that explores the dark and miserable town, Basin City, and tells the story of three different people, all caught up in violent corruption.",
                            Title = "Sin City"
                        },
                        new
                        {
                            Id = new Guid("9401f859-81fc-4689-89c2-9b54d1e956b8"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An aging, booze-addled father makes the trip from Montana to Nebraska with his estranged son in order to claim a million-dollar Mega Sweepstakes Marketing prize.",
                            Title = "Nebraska"
                        },
                        new
                        {
                            Id = new Guid("c7178539-6472-4c4d-94e3-5f7493a8d95d"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2001, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "After his swamp is filled with magical creatures, an ogre agrees to rescue a princess for a villainous lord in order to get his land back.",
                            Title = "Shrek"
                        },
                        new
                        {
                            Id = new Guid("024defb1-2da8-44aa-b72e-a7ea7bbec205"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2005, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A bored married couple is surprised to learn that they are both assassins hired by competing agencies to kill each other.",
                            Title = "Mr. & Mrs. Smith"
                        },
                        new
                        {
                            Id = new Guid("ffe277b6-3876-423e-bd7f-a5bf4b4c64af"),
                            Rating = "4",
                            ReleaseDate = new DateTime(2001, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A woman along with her lover, plan to con a rich man by marrying him and on earning his trust running away with all his money. Everything goes as planned until she actually begins to fall in love with him.",
                            Title = "Original Sin"
                        },
                        new
                        {
                            Id = new Guid("cfc4683e-6aa4-4c44-b145-1c1dbf1c745e"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Rumpelstiltskin tricks a mid-life crisis burdened Shrek into allowing himself to be erased from existence and cast in a dark alternate timeline where Rumpel rules supreme.",
                            Title = "Shrek Forever After"
                        },
                        new
                        {
                            Id = new Guid("a600c660-d635-4134-86a0-b9acfdaad489"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "We meet Jesse and Celine nine years on in Greece. Almost two decades have passed since their first meeting on that train bound for Vienna.",
                            Title = "Before Midnight"
                        },
                        new
                        {
                            Id = new Guid("51186f62-f718-4ce8-9a6a-f1f960b00579"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2010, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "When a criminal mastermind uses a trio of orphan girls as pawns for a grand scheme, he finds their love is profoundly changing him for the better.",
                            Title = "Despicable Me"
                        },
                        new
                        {
                            Id = new Guid("6146d395-e6c0-4825-ab4c-17ac1229c664"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An adaptation of Homer's great epic, the film follows the assault on Troy by the united Greek forces and chronicles the fates of the men involved.",
                            Title = "Troy"
                        },
                        new
                        {
                            Id = new Guid("587c9c64-9dea-4f2c-a9a4-458c36603242"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2012, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home - and the gold within it - from the dragon Smaug.",
                            Title = "The Hobbit: An Unexpected Journey"
                        },
                        new
                        {
                            Id = new Guid("89f083a9-382e-4cc4-ac25-69611636091e"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A writer and wall street trader, Nick, finds himself drawn to the past and lifestyle of his millionaire neighbor, Jay Gatsby.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("b2e98313-3bad-4d11-8687-8fd2544e2429"),
                            Rating = "3",
                            ReleaseDate = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Set during the Ice Age, a sabertooth tiger, a sloth, and a wooly mammoth find a lost human infant, and they try to return him to his tribe.",
                            Title = "Ice Age"
                        },
                        new
                        {
                            Id = new Guid("fa30eaca-8949-494c-b6cd-31ea3db2ca66"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2001, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle Earth from the Dark Lord Sauron.",
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = new Guid("11104adf-5b33-4da6-8586-8153cb5fb217"),
                            Rating = "8",
                            ReleaseDate = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            Title = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            Id = new Guid("1e9fb5bf-8b6d-4500-87ae-3ffe3cf55494"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2015, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A young programmer is selected to participate in a ground-breaking experiment in synthetic intelligence by evaluating the human qualities of a breath-taking humanoid A.I.",
                            Title = "Ex Machina"
                        },
                        new
                        {
                            Id = new Guid("10b09bc4-85d7-4949-b6fd-2cba7fc92206"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A look at the relationship between the famous physicist Stephen Hawking and his wife.",
                            Title = "The Theory of Everything"
                        },
                        new
                        {
                            Id = new Guid("6562160e-da58-40bd-a331-285123acbe35"),
                            Rating = "4",
                            ReleaseDate = new DateTime(1980, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A English navigator becomes both a player and pawn in the complex political games in feudal Japan.",
                            Title = "Shogun"
                        },
                        new
                        {
                            Id = new Guid("02360b56-7e67-489d-a3b8-0043f03c8a86"),
                            Rating = "5",
                            ReleaseDate = new DateTime(2015, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.",
                            Title = "Spotlight"
                        },
                        new
                        {
                            Id = new Guid("9063a24c-f013-41d6-89ce-2f1f15343804"),
                            Rating = "9",
                            ReleaseDate = new DateTime(1958, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A San Francisco detective suffering from acrophobia investigates the strange activities of an old friend's wife, all the while becoming dangerously obsessed with her.",
                            Title = "Vertigo"
                        },
                        new
                        {
                            Id = new Guid("fd1e6844-1008-403b-b170-841e0eaea3e6"),
                            Rating = "1",
                            ReleaseDate = new DateTime(2014, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = new Guid("f281395a-2ff0-4605-bd96-1ca9909017ed"),
                            Rating = "2",
                            ReleaseDate = new DateTime(2006, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.",
                            Title = "The Lives of Others"
                        },
                        new
                        {
                            Id = new Guid("48fc278f-78a8-4349-a51c-5b7f4017600a"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Paul Rusesabagina was a hotel manager who housed over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda.",
                            Title = "Hotel Rwanda"
                        },
                        new
                        {
                            Id = new Guid("e3ec33f7-16b6-4352-ba45-f5ceacb5ddd1"),
                            Rating = "0",
                            ReleaseDate = new DateTime(2015, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = new Guid("04e33ec0-b6c4-44d8-ad4c-7164e106a9ef"),
                            Rating = "2",
                            ReleaseDate = new DateTime(1962, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his kids against prejudice.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("9580b393-5253-4676-808f-9d8155513b57"),
                            Rating = "7",
                            ReleaseDate = new DateTime(2015, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
                            Title = "The Hateful Eight"
                        },
                        new
                        {
                            Id = new Guid("a417cdbd-1298-42de-80c3-5854961cfd48"),
                            Rating = "9",
                            ReleaseDate = new DateTime(2011, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "A married couple are faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer's disease.",
                            Title = "A Separation"
                        },
                        new
                        {
                            Id = new Guid("ed582c87-01ab-4c03-a3cf-9f392ae563e3"),
                            Rating = "8",
                            ReleaseDate = new DateTime(2015, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Synopsis = "Four denizens in the world of high-finance predict the credit and housing bubble collapse of the mid-2000s, and decide to take on the big banks for their greed and lack of foresight.",
                            Title = "The Big Short"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
